In [1]:
import torch
from torch import nn

X = torch.tensor([
    [10.0],
    [38.0],
    [100.0],
    [150.0]
])

model = nn.Linear(1, 1)

# Set the bias of the model to 32.0
model.bias = nn.Parameter(torch.tensor([32.0]))

# Set the weight of the model to 1.8
model.weight = nn.Parameter(torch.tensor([[1.8]]))

# Print the bias of the model
print(model.bias)

# Print the weight of the model
print(model.weight)

# Perform prediction with the model and print y_pred
y_pred = model(X)
print(y_pred)

Parameter containing:
tensor([32.], requires_grad=True)
Parameter containing:
tensor([[1.8000]], requires_grad=True)
tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)
